spring:
  datasource:
    username: root
    password: jinyi
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_system?characterEncoding=utf8
#    initialization-mode: always
#    data: classpath:sql/data.sql
server:
  port: 8081
